<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DevShelf.Domain\DevShelf.Domain.csproj" />
    <ProjectReference Include="..\DevShelf.Infrastructure\DevShelf.Infrastructure.csproj" />
  </ItemGroup>

</Project>
